"use client"
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { CreateEventForm, NewEventType } from "@/components/create-event-form";
import { events as initialEvents, Event } from "@/lib/events";
import { PlusCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";

// For now, we'll assume organizer with ID "1" is logged in.
const ORGANIZER_ID = "1";

export default function OrganizerDashboardPage() {
  const [isCreatingEvent, setIsCreatingEvent] = useState(false);
  // We use a state here just to trigger re-renders on this page when an event is added.
  // The actual source of truth will be the `initialEvents` array we import.
  const [, setForceRender] = useState(0);

  // We will now always derive the organizer's events directly from the main `initialEvents` list.
  const organizerEvents = initialEvents.filter(event => event.organizerId === ORGANIZER_ID);

  const handleEventCreated = (newEventData: NewEventType) => {
    const newEvent: Event = {
      // In a real app, the ID would be generated by the database
      id: (initialEvents.length + 1 + Math.random()).toString(), 
      ...newEventData,
      tags: newEventData.tags.split(',').map(tag => tag.trim()),
      organizerId: ORGANIZER_ID,
      longDescription: newEventData.longDescription,
    };
    
    // This is the key change: we directly modify the imported array.
    // This makes the new event available to all other pages that import it.
    initialEvents.unshift(newEvent);
    
    // We trigger a re-render for this component to show the new event in the list below.
    setForceRender(Math.random());
    setIsCreatingEvent(false);
  }

  return (
    <div className="container mx-auto px-4 py-12">
      <div className="flex justify-between items-center mb-8">
        <h1 className="text-4xl font-bold text-primary">Organizer Dashboard</h1>
        <Button onClick={() => setIsCreatingEvent(!isCreatingEvent)}>
          <PlusCircle className="mr-2" />
          {isCreatingEvent ? "Cancel" : "Create New Event"}
        </Button>
      </div>

      {isCreatingEvent ? (
        <CreateEventForm onFinished={() => setIsCreatingEvent(false)} onEventCreated={handleEventCreated} />
      ) : (
        <Card className="border-4 border-primary">
          <CardHeader>
            <CardTitle>Your Events</CardTitle>
            <CardDescription>Here are the events you've created.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {organizerEvents.length > 0 ? (
              organizerEvents.map(event => (
                <div key={event.id} className="flex items-center gap-4 p-4 border-4 border-primary rounded-lg">
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold">{event.title}</h3>
                    <p className="text-sm text-muted-foreground">{event.date} &bull; {event.location}</p>
                     <div className="flex flex-wrap gap-2 mt-2">
                        {event.tags.map(tag => <Badge key={tag} variant="secondary">{tag}</Badge>)}
                    </div>
                  </div>
                  <Button variant="outline" size="sm">Edit</Button>
                </div>
              ))
            ) : (
              <p className="text-center text-muted-foreground py-8">You haven't created any events yet.</p>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
}
